### ISSUE TITLE
Files fail to open in HTML view

### ISSUE THREAD

**Issue by Hoid-123** [MediaArea/MediaInfo#1084]
With latest version, 25.03, on Win 10, video files (.mkv, .mp4) fail to open when the HTML view is selected as default. 
(You must at least open one file) is displayed. 
I can select the HTML from the view drop down or change any settings and it displays correctly. 
I have completely removed everything associated with MediaInfo  and done a fresh install with no change in behavior. 
I also have version 24.xx installed on my laptop which displays correctly when opening the same files.  

This is the GUI version installed from the universal installer and the files are opened from the Explorer extension.

Any help or pointers would be much appreciated!

**Comment by JeromeMartinez** [comment]
I can not reproduce the issue, I am also with Win10 and MediaInfo 25.03 with the universal installer, HTML view as default view, I have MediaInfo closed, I right click on a .mkv file, I select "MediaInfo", and MediaInfo shows up with the file details.
any step I miss? Maybe the file name?

**Comment by cjee21** [comment]
This issue was present in 24.11 (#942) in some situations but should be fixed in 24.12 already. There are no changes to initialization or HTML in the VCL code between 24.12 and 25.03 ([comparison](https://github.com/MediaArea/MediaInfo/compare/v24.12...v25.03#diff-ad45e0d3e6311c81d8158055867ab84f3dd36b245a048b283123f0e1b01565bb)). There are just some fixes to text view and menu bar as well as setting for separate instance which only affects Windows 11 shell extension.

Cannot reproduce this issue too. There is a bug where HTML or Graph view is sometimes blank (grey colour and is actually wrong size/position as if you maximize the Window will see a white rectangle) and need to restart MediaInfo to get it to work properly again but this is likely a VCL bug in how it initializes the HTML engine.

https://github.com/user-attachments/assets/91b43857-2fac-460c-a8cb-553dd9f933d1

Furthermore, we already have a refresh right after opening files passed via command line by the shell extension so I don't see why it would still act like there are no files open until another manual refresh by clicking HTML in the view menu:

https://github.com/MediaArea/MediaInfo/blob/06f1b659f57c081fabdc91d3f3546b73206e171c/Source/GUI/VCL/GUI_Main.cpp#L269-L289

**Comment by cjee21** [comment]
@JeromeMartinez Found the way to reproduce. Only happens when using IE engine. Theme does not matter. Does not happen when using Edge WebView2. No idea.

Side note: I thought virtually all Windows 10 and 11 PCs should have WebView2 now since Microsoft said they are auto installing it and recent versions even prevent uninstallation by not showing it in programs list but looks like no.

**Comment by Hoid-123** [comment]
Thanks for the replies, here's the steps I have taken:

- Uninstall MediaInfo, reboot
- Install MS Edge (I had previously deleted it thinking it was obtrusive bloat)
- Reinstall MediaInfo - no change, bug still only shows up with HTML default.
- Uninstall Edge and MediaInfo via BCUninstaller and remove all associated registry keys, reboot
- Reinstall both, no change
- Attempt to install MicrosoftEdgeWebview2Setup.exc, failed, installer says already installed
- Uninstall K-Lite Codec Pack as it contains MediaInfo Lite 
- Uninstall MediaInfo, reboot
- Reinstall MediaInfo, still no change.

I'm sorry for the issues because it seems like it stems from me deleting Edge but I can't figure why it still will not work after reinstalling everything. 

Thanks for your time.

**Comment by cjee21** [comment]
I think I found a way to prevent this issue from happening but that does not explain why EdgeWebView2 is not used when it appears to be installed.

**Comment by cjee21** [comment]
@JeromeMartinez I think that's the wrong snapshot link...

**Comment by Hoid-123** [comment]
So firstly here's a snapshot of the the context menu, not sure if you need it any more but I included it anyway.
I downloaded your snapshot and tried to install but it failed attempting to write the infotip.dll file.  I aborted and canceled the installer, then went to open MediaInfo, it pops up preferences window like a new install and everything so far works, HTML opens on default window w/o refresh and the infotip still works. 
Not sure if this is of any use to you but I noticed in the Program Files folder after the failed install that the Mediainfo.exc, history, license and readme files all were modified from the failed update today, 3 of the .dll files show a 3/21-22 date from the 25.03 update but the WebView2Loader.dll mod date is 8/6/2024. Like I said not sure if that's any use to you, it just kinda stuck out to me after the failed update.

On a somewhat side note I used to have that infotip install fail happen all the time when updating K-Lite pack where it would sometimes actually stop the infotip from working at all. 

Let me know if there's anything else I can do to help.

![Image](https://github.com/user-attachments/assets/25be4f5e-c25a-40b7-b9f7-b5c4260831ee)

![Image](https://github.com/user-attachments/assets/80d6245f-f4e0-4341-b518-68660f0d882f)

![Image](https://github.com/user-attachments/assets/eefe7587-b070-4a01-96c4-704dbef6a158)

**Comment by cjee21** [comment]
@Hoid-123 That context menu shows it is using IE so your Edge WebView2 is not used / not working properly (as you said installer says already installed). Just letting you know, does not really matter since it can work with IE properly now.

@JeromeMartinez Looks like when ToolTip is enabled, it will fail to update according to above post? Does it not unload from Explorer when not active?

**Comment by JeromeMartinez** [comment]
> Looks like when ToolTip is enabled, it will fail to update according to above post? Does it not unload from Explorer when not active?

It does but sometimes it is locked due to a infinite loop or something similar, and it is resolved after a restart.
Anyway, ignoring it here does not impact the result of the installation.

**Comment by JeromeMartinez** [comment]
@Hoid-123 is the initial issue resolved with the snapshot?
(the fail in the infotip is not a problem for the test, the GUI has been updated)

**Comment by Hoid-123** [comment]
@JeromeMartinez yes, the HTML view now opens correctly with it set as default.
